"""empty message

Revision ID: 0d92d60e125d
Revises: 2f67f957357e
Create Date: 2019-09-10 17:34:00.379567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d92d60e125d'
down_revision = '2f67f957357e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'body')
    # ### end Alembic commands ###
