"""empty message

Revision ID: 7b675c567224
Revises: e05649293d26
Create Date: 2019-09-09 15:29:16.627854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b675c567224'
down_revision = 'e05649293d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'flags', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'flags', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flags', type_='foreignkey')
    op.drop_constraint(None, 'flags', type_='foreignkey')
    # ### end Alembic commands ###
