"""empty message

Revision ID: e05649293d26
Revises: 26fa89df21b4
Create Date: 2019-09-09 15:09:35.685270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05649293d26'
down_revision = '26fa89df21b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flags', sa.Column('post_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flags', 'post_id')
    # ### end Alembic commands ###
